name: 'Terraform Deploy'

on: 
  workflow_call:

    inputs:
      terraform_version:
        description: 'The version of Terraform to use'
        required: false
        type: string
        default: '1.5.0'
      aws_region:
        description: 'aws region to deploy resources'
        required: true
        type: string


jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ inputs.aws_region }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraform_version }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
